name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run SUT and wait for startup
        run: |
          # Запускаем приложение в фоне
          java -jar artifacts/app-replan-delivery.jar &
          
          # Ждем пока приложение станет доступно
          echo "Waiting for application to start..."
          for i in {1..30}; do
            if curl -f http://localhost:9999 > /dev/null 2>&1; then
              echo "Application is ready!"
              break
            fi
            echo "Waiting... attempt $i"
            sleep 2
          done

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test --info
        env:
          SELENIDE_HEADLESS: true

      - name: Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: build/test-results/test/**/*.xml
          reporter: java-junit